### ISSUE TITLE
_blank not blank

### ISSUE THREAD

**Issue by the-sides** [Jarvvski/Start-Page#1]
For the target attribute on the <a> tags, "blank" will not have an effort, whereas "_blank" will. Otherwise, opening a new link will replace the first link opened. Otherwise with the underscore, links will open independently

**Comment by Jarvvski** [comment]
I don't use this homepage anymore, but I believe I did that on purpose at the time of writing for the very reasons your describing

This isn't a _bug_, more just one of two possible variations. Just fork and use that for your own homepage instead

**Comment by the-sides** [comment]
Gotcha, I briefly looked into it and
